#ABC reporting: Compute the revenue generated by each customer based on their orders.
# Also, show each customer's revenue as a percentage of total revenue. 
# Sort by customer name.

SELECT 	customerName,
		SUM(quantityOrdered*priceEach) As 'Revenue Generated',
        ROUND(100*(SUM(quantityOrdered*priceEach)) / (
        SELECT SUM(quantityOrdered*priceEach) FROM OrderDetails
        ),2) AS Percentage
FROM Customers AS c
JOIN Orders AS o ON o.customerNumber=c.customerNumber
JOIN OrderDetails AS d ON d.orderNumber=o.orderNumber
GROUP BY customerName
ORDER BY customerName;