# Compute the profit generated by each customer based on their orders. Also, show 
# each customer's profit as a percentage of total profit. Sort by profit descending.

SELECT 	customerName,
		ROUND(SUM( quantityOrdered* (priceEach-buyPrice) ),2) AS 'Profit' ,
        ROUND(100*SUM(quantityOrdered*(priceEach-buyPrice)) / (
        SELECT SUM(quantityOrdered*(priceEach-buyPrice)) FROM OrderDetails AS od
        JOIN Products AS pr ON pr.productCode=od.productCode
        ),2) AS 'Percentage of profit'
FROM Customers AS c
JOIN Orders AS o ON c.customerNumber = o.customerNumber
JOIN OrderDetails AS d ON d.orderNumber = o.orderNumber
JOIN Products AS p ON d.productCode = p.productCode
GROUP BY customerName
ORDER BY Profit DESC