# Compute the revenue generated by each sales representative based on the 
# orders from the customers they serve.

SELECT 	employeeNumber,
		CONCAT(firstname,' ',lastname) AS employeeName,
        ROUND(SUM(quantityOrdered*priceEach),2) AS customerOrders
FROM Employees AS e
JOIN Customers AS c ON c.salesRepEmployeeNumber = e.employeeNumber
JOIN Orders AS o ON o.customerNumber = c.customerNumber
JOIN OrderDetails AS d ON d.orderNumber=o.orderNumber
GROUP BY employeeNumber
ORDER BY customerOrders DESC;