# Compute the profit generated by each sales representative based on the orders 
# from the customers they serve. Sort by profit generated descending.

SELECT 	employeeNumber,
		CONCAT(firstname,' ',lastname) AS employeeName,
        ROUND(SUM(quantityOrdered*(priceEach-buyPrice)),2) AS totalProfit
FROM Employees AS e
JOIN Customers AS c ON c.salesRepEmployeeNumber = e.employeeNumber
JOIN Orders AS o ON o.customerNumber = c.customerNumber
JOIN OrderDetails AS d ON d.orderNumber=o.orderNumber
JOIN Products AS p ON p.productCode = d.productCode
GROUP BY employeeNumber
ORDER BY totalProfit DESC;