# Compute the revenue generated by each product, sorted by product name.

SELECT 	p.productName AS 'Product Name',
		d.productCode AS 'Product Code',
		ROUND(SUM(quantityOrdered*priceEach),2) AS Profit
FROM OrderDetails AS d
JOIN Products AS p ON d.productCode=p.productCode
GROUP BY d.productCode
ORDER BY p.productName