#Compute the profit generated by each product line, sorted by profit descending.

SELECT productLine, SUM(quantityOrdered*(priceEach-buyPrice)) AS Profit FROM Products AS p
JOIN OrderDetails AS d ON p.productCode=d.productCode
GROUP BY productLine
ORDER BY Profit DESC